### ISSUE TITLE
general updates to the setup action

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/setup-dart#62]
We could likely use a general update to the action. Some things we'd want to include:

- [x] use patch versions in our versioning scheme (even if they're always zero). currently we use major.minor, which is non-standard (https://github.com/dart-lang/setup-dart/issues/71)
- [x] refactor the implementation of the action into Dart
- [x] auto-detect macos arm; https://github.com/dart-lang/setup-dart/issues/59
- [x] support version segment placeholder; #56 
- [ ] consider revising and improving our caching for provisioning the dart sdk https://github.com/dart-lang/setup-dart/issues/2
- [ ] consider adding auto-caching for pub packages / the pub cache

Additionally, the implementation of this action is in bash; we may consider refactoring it into Dart; this will give us access to some std libraries from github - like for caching - and generally make the action easier to maintain.
